Lazy loading Twig extensions
BitBagCommerce/SyliusCmsPlugin pull request #341
Opened 2021-01-12 14:10 UTC by crackgm

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | mentioned in #282 
| License         | MIT

2021-01-13 07:50 UTC, senghe requested changes
1. The functionality isn't fully tested.
2. Do we have rule in entire plugin to silently return empty values when data not found?

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderBlockRuntime.php
> +            $template = $template ?? '@BitBagSyliusCmsPlugin/Shop/Block/show.html.twig';
The @BitBagSyliusCmsPlugin/Shop/Block/show.html.twig should be put into private constant

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderBlockRuntime.php
> +        return '';
Why returning empty string? If we didn't find block, I would rather throw exception (or is it business condition?)

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderLinkRuntime.php
> +            return isset($options['notFoundMessage']) ? $options['notFoundMessage'] : '';
Is this a business rule to render empty string on negative path?

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderMediaRuntime.php
> +        return '';
Same here about empty value

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderProductPagesRuntime.php
> +        $data = $this->sortBySections($pages);
I don't see any test scenario for sortings

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderProductPagesRuntime.php
> +        if (null !== $sectionCode) {
I don't see full coverage for all scenarios for this condition

2021-01-13 07:50 UTC, senghe commented on src/Twig/Runtime/RenderMediaRuntime.php
> +        return '';
I don't see test for this return value

2021-01-13 14:48 UTC, crackgm commented on src/Twig/Runtime/RenderLinkRuntime.php
> +            return isset($options['notFoundMessage']) ? $options['notFoundMessage'] : '';
It's a business rule

2021-01-13 14:49 UTC, crackgm commented on src/Twig/Runtime/RenderBlockRuntime.php
> +            $template = $template ?? '@BitBagSyliusCmsPlugin/Shop/Block/show.html.twig';
Extracted this string into constant

2021-01-13 14:50 UTC, crackgm commented on src/Twig/Runtime/RenderBlockRuntime.php
> +        return '';
It's business rule

2021-01-13 14:50 UTC, crackgm commented on src/Twig/Runtime/RenderMediaRuntime.php
> +        return '';
It's also business rule

2021-01-13 14:51 UTC, crackgm commented on src/Twig/Runtime/RenderProductPagesRuntime.php
> +        $data = $this->sortBySections($pages);
Extracted sortBySections into new service and tested it

2021-01-13 14:51 UTC, crackgm commented on src/Twig/Runtime/RenderMediaRuntime.php
> +        return '';
Added missing test

2021-01-14 08:19 UTC, senghe requested changes

2021-01-14 08:19 UTC, senghe commented on spec/Sorter/SectionsSorterSpec.php
> +        $this->sortBySections([$page])->shouldReturn(
When we sort, we should to write test with at least 3 elements (and good would be to have at least test with correctly sorted input and untidy one).

2021-01-14 08:19 UTC, senghe commented on spec/Sorter/SectionsSorterSpec.php
> +        $this->sortBySections([$page])->shouldReturn(
Additionally, we have a condition inside a method - best would be to have two tests - one which goes into it and second, which doesn't.

2021-01-14 09:42 UTC, crackgm commented on spec/Sorter/SectionsSorterSpec.php
> +        $this->sortBySections([$page])->shouldReturn(
Added more tests

2021-01-14 09:43 UTC, merged