ECS fixes; OPSRC-405
BitBagCommerce/SyliusCmsPlugin pull request #404
Opened 2021-11-23 12:40 UTC by piotrleo

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | applies ECS fixes, OPSRC-405
| License         | MIT

2021-11-23 13:10 UTC, kptLucek commented
.

2021-11-24 12:37 UTC, piotrleo commented on src/Twig/Runtime/RenderLinkRuntime.php
> +            throw new NotFoundHttpException('Page for code ' . $code . ' not found');
I don't get it, WDYM by "put argument into quotes"?

2021-11-24 13:35 UTC, piotrleo commented on src/Controller/PageController.php
> +        $pageTranslationInterface->setImage($image);
I don't know where is it copy-pasted in code fragment you highlighted. But I've done some refactoring to remove duplicates.

2021-11-24 21:04 UTC, piotrleo commented on phpstan.neon
> +        - 'tests/Fixture/PageFixtureTest.php'
'tests/Fixture/PageFixtureTest.php' depends on Behat, which is not obligatory for this plugin

2021-11-25 09:02 UTC, er1z requested changes

2021-11-25 09:02 UTC, er1z commented on src/Twig/Extension/RenderProductPagesExtension.php
> +        $pageRepository = $this->entityManager->getRepository(Page::class);
Inject repository as a constructor argument.

2021-11-25 09:02 UTC, er1z commented on src/Twig/Runtime/RenderLinkRuntime.php
> +            throw new NotFoundHttpException('Page for code ' . $code . ' not found');
`'Page for code "' . $code . '" not found'`

2021-11-25 10:25 UTC, piotrleo commented on src/CustomResourceController.php
> +abstract class CustomResourceController extends ResourceController
Actually I had no idea how to name it properly. Any suggestions would really help me

2021-12-01 10:28 UTC, er1z requested changes

2021-12-01 10:28 UTC, er1z commented on src/Controller/BlockController.php
> +            Assert::true(null !== $this->viewHandler, 'View handler is null');
If you use Webmozart's library, you can check `Assert::isNotNull` which is better in terms of readability.

2021-12-01 10:28 UTC, er1z commented on src/Controller/BlockController.php
> +            Assert::true(null !== $this->viewHandler, 'View handler is null');
As above.

2021-12-01 10:28 UTC, er1z commented on src/Importer/BlockImporter.php
> +        $this->entityManager->persist($block);
Why not `Repository::add`?

2021-12-01 10:28 UTC, er1z commented on src/Importer/MediaImporter.php
> +        $this->entityManager->persist($media);
Why not `Repository::add`?

2021-12-01 10:28 UTC, er1z commented on src/Sorter/SectionsSorter.php
> +                Assert::notNull($sectionCode);
Besides, why don't break this into private methods?

2021-12-01 10:28 UTC, er1z commented on src/Twig/Parser/ContentParser.php
> +        if (!is_callable($callback)) {
`Assert` class contains `isCallable` method.

2021-12-01 10:28 UTC, er1z commented on tests/Behat/Resources/services/pages.yml
> +          [ 'behat.mink.default_session', 'behat.mink.parameters' ]
New line at the end of file, please.

2021-12-01 10:28 UTC, er1z commented on src/Controller/MediaController.php
> +    private function setResourceMediaPathIfExists(MediaInterface $media): void
What does it do?

2021-12-01 10:28 UTC, er1z commented on src/Controller/ResourceDataProcessingTrait.php
> +        $file = $media->getFile() ?? new File($this->getParameter('sylius_core.public_dir') . '/' . $media->getPath());
Extract it via CacheResolver; the image can be locally stored file or cloud one, so if you decide to fetch it this way: only the further will be working.

2021-12-01 11:13 UTC, piotrleo commented on src/Twig/Parser/ContentParser.php
> +        if (!is_callable($callback)) {
Right, I've had it done, but reverted and forgot about it

2021-12-01 11:15 UTC, piotrleo commented on src/Controller/BlockController.php
> +            Assert::true(null !== $this->viewHandler, 'View handler is null');
I know, but NotNull gave me an error in phpstan for Sylius 1.8, coz the change to ViewHandler has been made when Sylius was updated to 1.9. Earlier the ViewHandler was not nullable.

2021-12-01 11:16 UTC, piotrleo commented on src/Controller/BlockController.php
> +            Assert::true(null !== $this->viewHandler, 'View handler is null');
As above, these are only two cases where I wrote it like this.

2021-12-01 11:16 UTC, piotrleo commented on tests/Behat/Resources/services/pages.yml
> +          [ 'behat.mink.default_session', 'behat.mink.parameters' ]
Sure :)

2021-12-02 07:24 UTC, piotrleo commented on src/Controller/MediaController.php
> +    private function setResourceMediaPathIfExists(MediaInterface $media): void
Yeah, it was stupid function, I've just removed it :)

2021-12-02 07:33 UTC, piotrleo commented on src/Importer/MediaImporter.php
> +        $this->entityManager->persist($media);
Done

2021-12-02 07:37 UTC, piotrleo commented on src/Twig/Parser/ContentParser.php
> +        if (!is_callable($callback)) {
Done

2021-12-02 07:37 UTC, piotrleo commented on tests/Behat/Resources/services/pages.yml
> +          [ 'behat.mink.default_session', 'behat.mink.parameters' ]
Done

2021-12-02 07:37 UTC, piotrleo commented on src/Importer/BlockImporter.php
> +        $this->entityManager->persist($block);
Done

2021-12-03 14:25 UTC, piotrleo commented on src/Sorter/SectionsSorter.php
> +                Assert::notNull($sectionCode);
Done

2021-12-03 14:27 UTC, piotrleo commented on src/Controller/ResourceDataProcessingTrait.php
> +        $file = $media->getFile() ?? new File($this->getParameter('sylius_core.public_dir') . '/' . $media->getPath());
There are not only images, I left it like it was before

2021-12-06 13:02 UTC, er1z commented on src/Controller/ResourceDataProcessingTrait.php
> +    }
Isn't the amount of logic too large for a single trait…?

2021-12-07 15:54 UTC, piotrleo commented on src/Twig/Parser/ContentParser.php
> +        Assert::isArray($callable, sprintf('Function with name "%s" is not callable', $functionName));
Wdym by redundant? Get callable can also be null and stan gives following errors:
```
  88     Cannot access offset 0 on (callable(): mixed)|null.  
  89     Cannot access offset 1 on (callable(): mixed)|null.  
```

2021-12-07 16:16 UTC, piotrleo commented on src/Controller/ResourceDataProcessingTrait.php
> +    }
You're right, done

2021-12-08 10:19 UTC, piotrleo commented on src/Twig/Parser/ContentParser.php
> +        Assert::isArray($callable, sprintf('Function with name "%s" is not callable', $functionName));
I'm responding in here to the first comment in this CR, coz I have no possibilty to respond to that. What I meant in commit message was that I added custom Assert error messages. I will remove redundant ones, which are generic like `'View handler is null'`

2021-12-08 10:24 UTC, piotrleo commented on src/Twig/Parser/ContentParser.php
> +        Assert::isArray($callable, sprintf('Function with name "%s" is not callable', $functionName));
Done

2021-12-08 10:54 UTC, er1z commented on src/Controller/MediaController.php
> +        Assert::string($this->getParameter('sylius_core.public_dir'), 'sylius_core.public_dir is not string');
Do we still deal with locally stored asset?

2021-12-08 10:54 UTC, er1z commented on src/Controller/ResourceDataProcessingTrait.php
> +        $file = new File($this->getParameter('sylius_core.public_dir') . $media->getPath());
Doesn't `MediaController` contain similar code?

2021-12-08 10:54 UTC, er1z commented on src/Twig/Parser/ContentParser.php
> +        Assert::isArray($callable, sprintf('Function with name "%s" is not callable', $functionName));
I meant that passing `$callable` array directly to `isCallable` and thus to the callback is solving the same problem with a less amount of code. :)

2021-12-10 12:36 UTC, er1z commented on src/Controller/MediaController.php
> +    use CommonSetterDependencyInjectionsTrait;
How about renaming to more context-specific?

2021-12-10 12:36 UTC, er1z commented on src/Resources/assets/admin/js/index.js
> +if (document.querySelector('[data-bb-target="cms-import"]')) {
Is it intentional that a few scenarios can happen at once?

2021-12-10 12:36 UTC, er1z commented on src/Resources/public/build/manifest.json
> +}
New line at the end?

2021-12-10 12:36 UTC, er1z commented on tests/Application/assets/shop/entry.js
> +import 'sylius/bundle/ShopBundle/Resources/private/entry';
Empty line missing.

2021-12-10 12:43 UTC, piotrleo commented on src/Resources/assets/admin/js/index.js
> +if (document.querySelector('[data-bb-target="cms-import"]')) {
It's actually change from master, I'll leave it without changes but we can take up the topic on os-ongoing

2021-12-10 12:44 UTC, piotrleo commented on src/Resources/public/build/manifest.json
> +}
Done

2021-12-10 12:44 UTC, piotrleo commented on tests/Application/assets/shop/entry.js
> +import 'sylius/bundle/ShopBundle/Resources/private/entry';
Done

2021-12-10 13:05 UTC, piotrleo commented on src/Controller/MediaController.php
> +    use CommonSetterDependencyInjectionsTrait;
Done

2021-12-15 10:15 UTC, er1z commented on src/Controller/MediaController.php
>          if ($form->isValid()) {
Can this block be extracted to private method? Nesting too much causes code to be less readable.

2021-12-15 10:36 UTC, er1z approved these changes

2021-12-15 10:49 UTC, merged