Opsrc 185 cms add data collector for cms plugin
BitBagCommerce/SyliusCmsPlugin pull request #434
Opened 2022-06-24 15:40 UTC by MrPogos

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2022-07-03 17:33 UTC, senghe requested changes

2022-07-03 17:33 UTC, senghe commented on src/Resources/views/DataCollector/block_collector.html.twig
> +{% extends '@WebProfiler/Profiler/layout.html.twig' %}
Could you translate the view? I don't know wether there is any possibility of having translated toolbar, but if so, it would use the translations.

2022-07-03 17:33 UTC, senghe commented on src/Resources/views/DataCollector/block_collector.html.twig
> +    {# Optional, for showing the most details. #}
I think the comment is redundant.

2022-07-03 17:33 UTC, senghe commented on src/Twig/Runtime/RenderBlockRuntime.php
> +            $this->blockRenderingHistory->startRenderingBlock($block);
```suggestion
            $this->blockRenderingHistory->recordRenderingBlock($block);
```

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/BlockRenderingHistory.php
> +final class BlockRenderingHistory implements BlockRenderingHistoryInterface
```suggestion
final class BlockRenderingEventRecorder implements BlockRenderingEventRecorderInterface
```

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/BlockRenderingHistory.php
> +    public function startRenderingBlock(BlockInterface $block): void
```suggestion
    public function recordRenderingBlockEvent(BlockInterface $block): void
```

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/BlockRenderingHistory.php
> +    public function getRenderedHistory(): array
```suggestion
    public function getRecordedEvents(): array
```

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/BlockRenderingHistory.php
> +    private $currentlyRendered = [];
```suggestion
    private $recordedEvents = [];
```

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/MediaRenderingHistory.php
> +final class MediaRenderingHistory implements MediaRenderingHistoryInterface
Could you refactor this class as I described in `BlockRenderingHistory` class?

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/PageRenderingHistory.php
> +final class PageRenderingHistory implements PageRenderingHistoryInterface
Could you refactor this class as I described in `BlockRenderingHistory` class?

2022-07-03 17:33 UTC, senghe commented on src/DataCollector/BlockRenderingHistory.php
> +final class BlockRenderingHistory implements BlockRenderingHistoryInterface
I would write specs for all classes like this

2022-07-06 19:37 UTC, senghe requested changes

2022-07-06 19:37 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +    function it_start_render_and_return_data(
```suggestion
    function it_starts_render_and_return_data(
```

Could you review all scenario names for correct english?

2022-07-06 19:37 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +class BlockRenderingEventRecorderSpec extends ObjectBehavior
Could you review all classes wether they're final?

2022-07-06 19:37 UTC, senghe commented on src/DataCollector/BlockRenderingEventRecorder.php
> +    public function getRecordedEvents(): array
```suggestion
    /** @return BlockInterface[] */
    public function getRecordedEvents(): array
```

2022-07-06 19:37 UTC, senghe commented on src/DataCollector/BlockRenderingEventRecorder.php
> +    /** @var array */
```suggestion
    /** @var BlockInterface[] */
```

2022-07-06 19:37 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +    function it_start_render(
Could you review all methods for missing return types?

2022-07-06 19:37 UTC, senghe commented on src/Resources/config/services/data_collector.yml
> +  bitbag_sylius_cms_plugin.profiler.block_history:
Could you review all service names and change it to match better the classes?

2022-07-06 19:37 UTC, senghe commented on src/Resources/views/DataCollector/block_collector.html.twig
> +        <span class="icon"><img src="..." alt=""/></span>
What does the `...` ?

2022-07-06 19:37 UTC, senghe commented on src/Twig/Runtime/RenderLinkRuntime.php
> +        LocaleContextInterface              $localeContext,
Could you run ECS?

2022-08-18 19:52 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +    function it_start_render(
Bump

2022-08-18 19:57 UTC, senghe requested changes

2022-08-18 19:57 UTC, senghe commented on src/Resources/config/services/data_collector.yml
> +  bitbag_sylius_cms_plugin.data_collector.page:
When you refactor class names, please don't forget about service ids! 👮

2022-08-18 19:57 UTC, senghe commented on src/Resources/views/DataCollector/block_collector.html.twig
> +{% extends '@WebProfiler/Profiler/layout.html.twig' %}
It still pops out.

2022-08-18 19:57 UTC, senghe commented on src/Twig/Runtime/RenderLinkRuntime.php
> +    private $pageRenderingHistory;
```suggestion
    private $pageRenderingEventRecorder;
```

2022-08-18 19:57 UTC, senghe commented on src/Twig/Runtime/RenderLinkRuntime.php
> +        PageRenderingEventRecorderInterface $pageRenderingHistory,
```suggestion
        PageRenderingEventRecorderInterface $pageRenderingEventRecorder,
```

2022-08-18 19:57 UTC, senghe commented on src/Twig/Runtime/RenderLinkRuntime.php
> +        $this->pageRenderingHistory->recordRenderingPageEvent($page);
```suggestion
        $this->pageRenderingEventRecorder->recordRenderingPageEvent($page);
```

2022-08-22 15:48 UTC, MrPogos commented on src/Resources/views/DataCollector/block_collector.html.twig
> +{% extends '@WebProfiler/Profiler/layout.html.twig' %}
WebProfiler does not support translation and other twig files do not use it, so I do not think that adding the translation in one place is a good practice

2022-08-28 20:42 UTC, senghe requested changes

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +    public function it_start_render(
```suggestion
    public function it_starts_rendering(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/BlockRenderingEventRecorderSpec.php
> +    public function it_start_render_and_clear_data(
```suggestion
    public function it_starts_rendering_and_clears_data(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/MediaRenderingEventRecorderSpec.php
> +    public function it_start_render(
```suggestion
    public function it_starts_rendering(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/MediaRenderingEventRecorderSpec.php
> +    public function it_starts_render_and_return_data(
```suggestion
    public function it_starts_rendering_and_returns_data(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/MediaRenderingEventRecorderSpec.php
> +    public function it_start_render_and_clear_data(
```suggestion
    public function it_starts_rendering_and_clears_data(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/PageRenderingEventRecorderSpec.php
> +    public function it_start_render(
```suggestion
    public function it_starts_rendering(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/PageRenderingEventRecorderSpec.php
> +    public function it_starts_render_and_return_data(
```suggestion
    public function it_starts_rendering_and_returns_data(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/PageRenderingEventRecorderSpec.php
> +    public function it_start_multi_render_and_return_data(
```suggestion
    public function it_starts_multirendering_and_returns_data(
```

2022-08-28 20:42 UTC, senghe commented on spec/DataCollector/PageRenderingEventRecorderSpec.php
> +    public function it_start_render_and_clear_data(
```suggestion
    public function it_starts_rendering_and_clears_data(
```

2022-08-28 20:42 UTC, senghe commented on src/DataCollector/CMSDataCollector.php
> +class CMSDataCollector extends Collector implements DataCollectorInterface
Why this class is not final?

2023-02-06 13:40 UTC, bitbager commented
Hi! Thanks for the PR. Any chance you could upgrade it according to @senghe's suggestions? 🙏

2023-03-20 09:37 UTC, rafalmal commented
It is outdated PR,  it seems incompleted and fails build.

2023-03-20 09:37 UTC, closed without merging