Add ability to save file while upload with original name instead of hash
BitBagCommerce/SyliusCmsPlugin pull request #456
Opened 2022-12-01 19:52 UTC by mariuszsokal-bitbag

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | none
| License         | MIT

2022-12-02 08:13 UTC, JakubWegner requested changes

2022-12-02 08:13 UTC, JakubWegner commented on src/Entity/Media.php
> +    /** @var bool|null */
Maybe default false will be better instead of null?

2022-12-02 08:13 UTC, JakubWegner commented on src/Uploader/MediaUploader.php
> +                $originalName = $file->getClientOriginalName();
Looks like it's `File`, not `UploadedFile`, so maybe try `SplFileInfo::getFilename()` to get the original file name

2022-12-02 08:13 UTC, JakubWegner commented on src/Uploader/MediaUploader.php
> +    ): string
Please use the PSR style `): string {`

2023-01-16 12:16 UTC, marekrzytki commented on src/Entity/Media.php
> +    /** @var bool|null */
Sure, changed to default false.

2023-01-16 12:18 UTC, marekrzytki commented on src/Uploader/MediaUploader.php
> +    ): string
Sure, fixed

2023-01-16 12:48 UTC, JakubWegner commented on src/Uploader/MediaUploader.php
> +                $originalName = $file->getClientOriginalName();
Looks good for me!

2023-01-16 13:08 UTC, JakubWegner approved these changes

2023-01-16 13:18 UTC, PiotrSzymanski2000 approved these changes

2023-01-16 14:41 UTC, liszkapawel approved these changes

2023-01-16 14:41 UTC, merged