Better Liip Imagine media integration
BitBagCommerce/SyliusCmsPlugin pull request #457
Opened 2022-12-12 22:28 UTC by David-Crty

| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes https://github.com/BitBagCommerce/SyliusCmsPlugin/issues/431  https://github.com/BitBagCommerce/SyliusCmsPlugin/issues/344
| License         | MIT

I have made some fixes about the `liip/gaufrette` integration, I only used the filter already available by sylius.

Please let me know if I need to do more about this MR :pray:

2023-04-03 05:50 UTC, rafalmal requested changes

2023-04-03 05:50 UTC, rafalmal commented on src/Resources/views/Shop/Media/Show/image.html.twig
> +{% if page.image.path starts with 'data:' %}
This change throws 500 error on main page.

2023-05-18 04:58 UTC, rafalmal commented on src/Resources/views/Shop/Media/Show/image.html.twig
> +{% if page.image.path starts with 'data:' %}
bump

2023-05-23 19:53 UTC, David-Crty commented on src/Resources/views/Shop/Media/Show/image.html.twig
> +{% if page.image.path starts with 'data:' %}
Can you show me the 500?

2024-05-22 07:21 UTC, marekrzytki commented on src/Resources/views/Shop/Media/Show/image.html.twig
> +{% if page.image.path starts with 'data:' %}
Hi @David-Crty. I also noticed this 500 error on fresh install with default fixtures.
![2024-05-22_09-18](https://github.com/BitBagCommerce/SyliusCmsPlugin/assets/61479357/8bd39fec-ac71-4993-bb87-7305cad18c42)

2024-06-18 07:43 UTC, senghe commented
I see no response since last month, so I'm closing this PR. Please reopen it if you still need it @David-Crty

2024-06-18 07:43 UTC, closed without merging