Op 278 - Add sylius 1.13 support
BitBagCommerce/SyliusCmsPlugin pull request #498
Opened 2024-06-03 08:18 UTC by SzymonKostrubiec

+ Apply changes from community pull request
+ Fixed a.gitignore  file
+ Added builds for nod 18.x
+ Restore google chrome driver in behat tests

2024-06-04 08:53 UTC, marekrzytki requested changes

2024-06-04 08:53 UTC, marekrzytki commented on composer.json
> -        "php": "^8.0",
Why PHP requirement is removed?

2024-06-04 08:53 UTC, marekrzytki commented on composer.json
> +    "sylius/sylius": "^1.12 || ^1.13",
"^1.12.0 || ^1.13.0",

2024-06-04 08:53 UTC, marekrzytki commented on phpunit.xml.dist
> -        <env name="APP_ENV" value="test"/>
Is this option not required in php unit 10.5?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> +    private function configureContainer(ContainerBuilder $container, LoaderInterface $loader): void
Why private?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> -        $syliusDir = $this->getProjectDir() . '/config/sylius/' . SyliusKernel::MAJOR_VERSION . '.' . SyliusKernel::MINOR_VERSION;
Why we are removing that? I'm pretty sure it's still required to load configuration files depending on Sylius version (1.12 or 1.13)

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> -        if (is_dir($syliusDir)) {
As mentioned above

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> -    protected function getContainerLoader(ContainerInterface $container): DelegatingLoader
Why we are removing this method?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> -        $routes->import($confDir . '/{routes}' . self::CONFIG_EXTS);
Why we are removing this methods?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/Kernel.php
> +        if ($this->isTestEnvironment()) {
You are sure this class always exist?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/config/bundles.php
> +    BitBag\SyliusCmsPlugin\BitBagSyliusCmsPlugin::class => ['all' => true],
Why do we add plugin bundle there?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/config/packages/liip_imagine.yaml
> -    loaders:
It's connected with Sylius update?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/package.json
> +{
Currently single package json in sufficient?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/config/sylius/1.12/packages/security.yaml
Why we are removing this file? Also where is updated version of security for Sylius 1.13? https://github.com/Sylius/Sylius/blob/1.14/UPGRADE-1.13.md#:~:text=Due%20to%20changes%20in%20API%20paths%2C%20the%20security%20configuration%20has%20been%20changed%3A

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/config/sylius/1.12/packages/jms_serializer.yaml
Why we are removing this config?

2024-06-04 08:53 UTC, marekrzytki commented on tests/Application/config/sylius/1.12/bundles.php
Why we are removing this config?

2024-06-04 10:09 UTC, SzymonKostrubiec commented on composer.json
> -        "php": "^8.0",
I have restored this dependency

2024-06-04 10:11 UTC, SzymonKostrubiec commented on phpunit.xml.dist
> -        <env name="APP_ENV" value="test"/>
Restored to original state

2024-06-04 10:12 UTC, SzymonKostrubiec commented on tests/Application/Kernel.php
> +    private function configureContainer(ContainerBuilder $container, LoaderInterface $loader): void
I have restored kernel file

2024-06-04 10:17 UTC, SzymonKostrubiec commented on tests/Application/config/bundles.php
> +    BitBag\SyliusCmsPlugin\BitBagSyliusCmsPlugin::class => ['all' => true],
It's required to use plugin correctly from test/Application,

2024-06-04 10:21 UTC, SzymonKostrubiec commented on tests/Application/package.json
> +{
Yes, the frontend library is sufficient to run the CmsPlugin

2024-06-04 10:49 UTC, marekrzytki requested changes

2024-06-04 10:49 UTC, marekrzytki commented on tests/Application/config/sylius/1.13/packages/security.yaml
> +security:
This file is not compatible with security changes from Sylius upgrade file: https://github.com/Sylius/Sylius/blob/1.14/UPGRADE-1.13.md -> point 11.
Also I think You are missing include in 1.13 bundles for Sylius\Abstraction\StateMachine\SyliusStateMachineAbstractionBundle::class => ['all' => true],

2024-06-04 11:33 UTC, merged

2024-06-27 20:13 UTC, Prometee commented
@marekrzytki @SzymonKostrubiec thank you for not mentioning me in the Release note, like I already mentioned: you are not engaging comunity by replacing the original PR creator.