OP-320: Add possibility to select section type and fill up collection of items of this type
BitBagCommerce/SyliusCmsPlugin pull request #500
Opened 2024-06-19 09:46 UTC by jkindly

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | OP-320, OP-312
| License         | MIT

2024-06-20 17:54 UTC, senghe requested changes

2024-06-20 17:54 UTC, senghe commented on spec/Assigner/CollectionsAssignerSpec.php
> +<?php
Missing BitBag OpenSource header comment. Could you add this to every file on which it is missing?

2024-06-20 17:54 UTC, senghe commented on spec/Assigner/CollectionsAssignerSpec.php
> +        CollectionableInterface       $collectionsAware
We don't use that style of indentation.

2024-06-20 17:54 UTC, senghe commented on spec/Importer/BlockImporterSpec.php
> +        ResourceResolverInterface            $blockResourceResolver,
Please fix the indentations in all files :pray:

2024-06-20 17:54 UTC, senghe commented on spec/Resolver/ImporterCollectionsResolverSpec.php
> +    {
```suggestion
    ) {
```

2024-06-20 17:54 UTC, senghe commented on src/Entity/Block.php
> +    use CollectionableTrait;
Collectible

2024-06-20 17:54 UTC, senghe commented on src/Entity/Block.php
> +        $this->initializeCollectionsCollection();
:joy:

2024-06-20 17:54 UTC, senghe commented on src/Entity/BlockableTrait.php
> +trait BlockableTrait
BlocksCollectionTrait

2024-06-20 17:54 UTC, senghe commented on src/Entity/BlockableInterface.php
> +interface BlockableInterface
BlocksCollectionInterface

2024-06-20 17:54 UTC, senghe commented on src/Entity/CollectionableInterface.php
> +interface CollectionableInterface
Collectible

2024-06-20 17:54 UTC, senghe commented on src/Entity/CollectionableTrait.php
> +trait CollectionableTrait
Collectible

2024-06-20 17:54 UTC, senghe commented on src/Entity/MediableInterface.php
> +interface MediableInterface
MediaCollectionInterface

2024-06-20 17:54 UTC, senghe commented on src/Entity/MediableTrait.php
> +trait MediableTrait
MediaCollectionTrait

2024-06-20 17:54 UTC, senghe commented on src/Entity/PageableInterface.php
> +interface PageableInterface
PagesCollectionInterface

2024-06-20 17:54 UTC, senghe commented on src/Entity/PageableTrait.php
> +trait PageableTrait
PagesCollectionTrait

2024-06-20 17:54 UTC, senghe commented on src/Resources/config/doctrine/Page.orm.xml
> +        <many-to-many field="collections" target-entity="BitBag\SyliusCmsPlugin\Entity\CollectionInterface">
How doctrine would behave with changing the field name, when we have a table with data? Isn't it safer to use the "sections" column name in all mapping places? The field can stay then as "collections".

2024-06-20 17:54 UTC, senghe commented on tests/Integration/Repository/CollectionRepositoryTest.php
> +class CollectionRepositoryTest extends JsonApiTestCase
Why not final?

2024-06-21 12:40 UTC, jkindly commented on src/Resources/config/doctrine/Page.orm.xml
> +        <many-to-many field="collections" target-entity="BitBag\SyliusCmsPlugin\Entity\CollectionInterface">
It doesn't change anything in the database. It is only related to the $collections field in entity, but in the database we have join-column-name: section_id

2024-06-24 18:40 UTC, senghe commented on src/Entity/BlockableTrait.php
> +trait BlockableTrait
This has not been changed yet

2024-06-24 18:41 UTC, senghe commented on src/Entity/BlockableInterface.php
> +interface BlockableInterface
huh?

2024-06-24 18:41 UTC, senghe commented on src/Entity/CollectionableInterface.php
> +interface CollectionableInterface
huh?

2024-06-24 18:41 UTC, senghe commented on src/Entity/MediableInterface.php
> +interface MediableInterface
huh?

2024-06-24 18:41 UTC, senghe requested changes
There are still some unresolved comments :vulcan_salute:

2024-06-25 08:05 UTC, senghe approved these changes

2024-06-25 08:05 UTC, merged