OP-326: New content elements
BitBagCommerce/SyliusCmsPlugin pull request #506
Opened 2024-07-08 10:20 UTC by jkindly

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | OP-326
| License         | MIT

2024-07-11 06:20 UTC, jkindly commented on src/Resources/assets/admin/js/bitbag/bitbag-content-configuration.js
> +/*
This script should be checked and refactored by someone from frontend team.

2024-07-12 05:55 UTC, senghe requested changes

2024-07-12 05:55 UTC, senghe commented on src/Form/DataTransformer/MultipleMediaToCodesTransformer.php
> +     */
We do not attach @throws annotations

2024-07-12 05:55 UTC, senghe commented on src/Form/Type/ContentConfigurationType.php
> +                    ];
It's a bit mess here. Could you order it a bit better?

2024-07-12 05:55 UTC, senghe commented on src/Repository/MediaRepository.php
> +            ->andWhere('o.name LIKE :name')
Couldn't we really do this in another way? LIKE %% has incredible bad performance...

2024-07-12 05:55 UTC, senghe commented on src/Resources/config/services/form.xml
> +        <service id="BitBag\SyliusCmsPlugin\Form\Type\ContentElements\ProductsCarouselByTaxonContentElementType">
Is this rule of naming standard for entire plugin?

2024-07-12 05:55 UTC, senghe commented on tests/Behat/Behaviour/ContainsContentElementTrait.php
> +        // so we need to check if input field with search class exists instead.
I'm not really sure whether we need a comment here, as the condition is really readable.

2024-07-12 05:55 UTC, senghe commented on tests/Behat/Context/Ui/Admin/BlockContext.php
> +     * @When I click on Add button in Content elements section
"Content" by capital "C"?

2024-07-12 05:55 UTC, senghe commented on tests/Behat/Page/Admin/Block/CreatePage.php
> +     * @throws ElementNotFoundException
We do not used to use @throws

2024-07-12 05:55 UTC, senghe commented on tests/Behat/Page/Admin/Page/CreatePage.php
> +        $addButton->waitFor(2, function (): bool {
I hope it is 2 ms, not 2 s :pray:

2024-07-12 06:44 UTC, jkindly commented on tests/Behat/Context/Ui/Admin/BlockContext.php
> +     * @When I click on Add button in Content elements section
Yes, because it is name of the section, not single content element, so I think it should be capitalized.

2024-07-12 08:49 UTC, jkindly commented on tests/Behat/Page/Admin/Page/CreatePage.php
> +        $addButton->waitFor(2, function (): bool {
It's seconds. All behat tests are written like this, even in Sylius core. I changed all occurrences to lower ones.

2024-07-12 09:07 UTC, jkindly commented on src/Repository/MediaRepository.php
> +            ->andWhere('o.name LIKE :name')
I agree, but there is already exact the same method in block, collection and pages. I just copied this one to the media. I'm not sure what we can change here. I was looking for a solution and didn't find anything special, except Elasticsearch or something similar. Maybe you have some idea?

2024-07-12 10:25 UTC, senghe approved these changes

2024-07-12 10:26 UTC, merged