OP-463: Block templates
BitBagCommerce/SyliusCmsPlugin pull request #515
Opened 2024-08-02 07:15 UTC by jkindly

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | OP-463
| License         | MIT

2024-08-06 18:19 UTC, senghe requested changes

2024-08-06 18:19 UTC, senghe commented on src/Menu/ContentManagementMenuBuilder.php
> +    private function reorderMenu(ItemInterface $menu, string $newItemKey, string $targetItemKey): void
I think there is too little specs. This private function potentially should be extracted to an external service and then fully specced, as it seems to be very complex and generic.

2024-08-06 18:19 UTC, senghe commented on tests/Behat/Page/Admin/Block/CreatePage.php
> +        $dropdown->waitFor(5, function () use ($templateName): bool {
If it is 5 seconds - for me it's too long.

2024-08-06 18:19 UTC, senghe commented on tests/Behat/Page/Admin/Block/CreatePage.php
> +        $this->getDocument()->waitFor(2, function (): bool {
Is there any chance to lower this to 1 second?

2024-08-12 12:32 UTC, jkindly commented on tests/Behat/Page/Admin/Block/CreatePage.php
> +        $dropdown->waitFor(5, function () use ($templateName): bool {
As I can see, 5 seconds is the max, if the callback will successfully fire earlier, it will break loop. Btw. 5 seconds is used in all tests.

2024-08-12 12:32 UTC, jkindly commented on tests/Behat/Page/Admin/Block/CreatePage.php
> +        $this->getDocument()->waitFor(2, function (): bool {
As my comment before.

2024-08-12 12:53 UTC, senghe approved these changes

2024-08-12 12:53 UTC, merged